{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oscar.fullname" . }}
  labels:
    {{- include "oscar.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- $fullname := include "oscar.fullname" $ }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /health
            pathType: Exact
            backend:
              service:
                name: {{ $fullname }}-api
                port:
                  number: {{ $.Values.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-api
                port:
                  number: {{ $.Values.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
